AutoShop/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Orden_Producto = new HashSet<Orden_Producto>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Favor de ingresar un nombre para el producto.")]
        [Display(Name = "Producto")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Favor de ingresar una categoría.")]
        [Display(Name = "Categoría")]
        public int id_categoria { get; set; }
        [Required(ErrorMessage = "Favor de ingresar una descripción.")]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [Display(Name = "Imagen")]
        public byte[] imagen { get; set; }
        [Required(ErrorMessage = "Favor de ingresar un precio.")]
        [Display(Name = "Precio")]
        [Range(1, 2000, ErrorMessage = "Favor de ingresar un precio valido ($1.00 - $2000.00)")]
        public decimal precio { get; set; }
        [Display(Name = "Descuento")]
        public Nullable<decimal> descuento { get; set; }
        [Required(ErrorMessage = "Favor de ingresar una cantidad.")]
        [Display(Name = "Cantidad")]
        [Range(1, 100, ErrorMessage = "Favor de ingresar una cantidad válida (1-100)")]
        public int cantidad { get; set; }

        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Producto> Orden_Producto { get; set; }
    }
}

AutoShop/Controllers/productoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoShop.Models;

namespace AutoShop.Controllers
{
    public class productoController : Controller
    {
        private contextAutoShop db = new contextAutoShop();

        // GET: producto
        public ActionResult Index()
        {
            var producto = db.Producto.Include(p => p.Categoria);
            return View(producto.ToList());
        }

        // GET: producto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: producto/Create
        public ActionResult Create()
        {
            ViewBag.id_categoria = new SelectList(db.Categoria, "id", "nombre");
            return View();
        }

        // POST: producto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nombre,id_categoria,descripcion,descuento,precio,cantidad")] Producto producto, HttpPostedFileBase imagen)
        {
            if (imagen != null && imagen.ContentLength > 0)
            {
                using (var reader = new System.IO.BinaryReader(imagen.InputStream))
                {
                    producto.imagen = reader.ReadBytes(imagen.ContentLength);
                }
            }
            if (ModelState.IsValid)
            {
                Producto prod = new Producto();
                prod.id = producto.id;
                prod.nombre = producto.nombre;
                prod.id_categoria = producto.id_categoria;
                prod.descripcion = producto.descripcion;
                prod.imagen = producto.imagen;
                prod.precio = producto.precio;
                prod.descuento = Descuento(producto.descuento);
                prod.cantidad = producto.cantidad;

                db.Producto.Add(prod);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Trace.TraceInformation("Property: {0} Error: {1}",
                                validationError.PropertyName,
                                validationError.ErrorMessage);
                        }
                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.id_categoria = new SelectList(db.Categoria, "id", "nombre", producto.id_categoria);
            return View(producto);
        }

        public decimal Descuento(decimal? desc)
        {
            decimal descuento = 0;
            switch (desc)
            {
                case 10:
                    descuento = 10;
                    break;
                case 20:
                    descuento = 20;
                    break;
                case 30:
                    descuento = 30;
                    break;
                case 40:
                    descuento = 40;
                    break;
                case 50:
                    descuento = 50;
                    break;
                case 60:
                    descuento = 60;
                    break;
                case 70:
                    descuento = 70;
                    break;
                case 80:
                    descuento = 80;
                    break;
                case 90:
                    descuento = 90;
                    break;
                case 100:
                    descuento = 100;
                    break;
            }
            return descuento;
        }


        // GET: producto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_categoria = new SelectList(db.Categoria, "id", "nombre", producto.id_categoria);
            return View(producto);
        }

        // POST: producto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre,id_categoria,descuento,descripcion,precio,cantidad")] Producto producto, HttpPostedFileBase imagen)
        {
            if (imagen != null && imagen.ContentLength > 0)
            {
                using (var reader = new System.IO.BinaryReader(imagen.InputStream))
                {
                    producto.imagen = reader.ReadBytes(imagen.ContentLength);
                }
            }
            if (ModelState.IsValid)
            {
                int id = producto.id;
                var prod = db.Producto.Find(id);
                decimal precio_ant = prod.precio;
                decimal precio_act = producto.precio;
                //db.Entry(producto).State = EntityState.Modified;
                prod.nombre = producto.nombre;
                prod.descripcion = producto.descripcion;
                prod.descuento = producto.descuento;
                prod.precio = producto.precio;
                prod.imagen = producto.imagen;
                prod.cantidad = producto.cantidad;
                prod.id_categoria = producto.id_categoria;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_categoria = new SelectList(db.Categoria, "id", "nombre", producto.id_categoria);
            return View(producto);
        }

        // GET: producto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Producto.Find(id);
            db.Producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //metodo para obtener imagen
        public ActionResult getImg(int id)
        {
            Producto imgPaq = (from i in db.Producto
                               where i.id == id
                               select i).ToList().FirstOrDefault();

            var fileToRetrieve = imgPaq.imagen;
            return File(fileToRetrieve, "image/jpeg");
        }

        public ActionResult getProductos()
        {
            var producto = db.Producto.OrderByDescending(e => e.id)
                .Include(p => p.Categoria).Take(5).ToList();
            return View(producto);
        }

        public ActionResult getExistencias()
        {
            var producto = db.Producto.OrderBy(e => e.cantidad)
                .Include(p => p.Categoria).Take(5).ToList();
            return View(producto);
        }

        public ActionResult getProdMayor()
        {
            var producto = db.Producto.OrderByDescending(e => e.cantidad)
                .Include(p => p.Categoria).Take(1).ToList();
            return View(producto);
        }



    }
}

AutoShop/Views/producto/Create.cshtml
@model AutoShop.Models.Producto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<div class="text-white sticky-title p-2" style="background-color: #e33b5c">
    <h1>Crear Producto</h1>
</div>

@using (Html.BeginForm(Html.BeginForm("Create", "producto", null, FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <div class="card" style="margin-top: 15px; background-color: rgb(255, 239, 239); border-color: #e33b5c">
            <div class="card-body" style="padding-left:3%; padding-top:3%; font-size:24px">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="offset-md-2 col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-12", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.id_categoria, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control col-md-10" })
                                        @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.descuento, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.DropDownListFor(model => model.descuento,
                            new List<SelectListItem>{
                                new SelectListItem { Value="10",Text="10%"},
                                new SelectListItem { Value="20",Text="20%"},
                                new SelectListItem { Value="30",Text="30%"},
                                new SelectListItem { Value="40",Text="40%"},
                                new SelectListItem { Value="50",Text="50%"},
                                new SelectListItem { Value="60",Text="60%"},
                                new SelectListItem { Value="70",Text="70%"},
                                new SelectListItem { Value="80",Text="80%"},
                                new SelectListItem { Value="90",Text="90%"},
                                new SelectListItem { Value="100",Text="100%"},
                            }, new {@class= "miselect  col-md-10", @style="width:100%; height:40px"})
                                        @Html.ValidationMessageFor(model => model.descuento, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group ml-3">
                                @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-12", @style = "text-align:left; font-size: 24px" })
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.imagen, new { @type = "file", @class = "form-control col-md-12", accept = ".jpg", id = "seleccionArchivos" })
                                    @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="offset-md-2 col-md-8 ">
                    <div class="card" style="margin-top: 15px; margin-left: 25px; margin-right: 25px; background-color: rgb(255, 239, 239); border-color: #e33b5c">
                        <div class="card-body">
                            <label>Imagen:</label>
                            <div class="row">
                                <div class="offset-md-2 col-md-8">
                                    <div class="card" style=" margin-left: 5%; margin-right: 5%; background-color: rgb(255, 239, 239); border-color: #e33b5c">
                                        <div class="card-body text-center">
                                            <img id="imagenPrevisualizacion" src="https://cdn.pixabay.com/photo/2017/01/25/17/35/picture-2008484_960_720.png" class="panel-img-top" height="250" width="300" alt="Card image cap">
                                        </div>
                                    </div>

                                </div>
                            </div>

                        </div>

                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="text-center">
                        <input type="submit" value="Guardar Producto" class="btn btn-danger" />
                    </div>
                </div>

            </div>
        </div>

    </div>
}

<script src="~/Scripts/Generados/Productos/Productos.js"></script>

AutoShop/Views/producto/Details.cshtml
@model AutoShop.Models.Producto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descuento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descuento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AutoShop/Views/producto/Edit.cshtml
@model AutoShop.Models.Producto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<div class="text-white sticky-title p-2" style="background-color: #e33b5c">
    <h1>Editar Producto</h1>
</div>

@using (Html.BeginForm(Html.BeginForm("Edit", "producto", null, FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="card" style="margin-top: 15px; background-color: rgb(255, 239, 239); border-color: #e33b5c">
            <div class="card-body" style="padding-left:3%; padding-top:3%; font-size:24px">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.id)
                <div class="row">
                    <div class="offset-md-2 col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-12", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.id_categoria, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control col-md-10" })
                                        @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.descuento, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.DropDownListFor(model => model.descuento,
                            new List<SelectListItem>{
                                new SelectListItem { Value="10",Text="10%"},
                                new SelectListItem { Value="20",Text="20%"},
                                new SelectListItem { Value="30",Text="30%"},
                                new SelectListItem { Value="40",Text="40%"},
                                new SelectListItem { Value="50",Text="50%"},
                                new SelectListItem { Value="60",Text="60%"},
                                new SelectListItem { Value="70",Text="70%"},
                                new SelectListItem { Value="80",Text="80%"},
                                new SelectListItem { Value="90",Text="90%"},
                                new SelectListItem { Value="100",Text="100%"},
                            }, new {@class= "miselect  col-md-10", @style="width:100%; height:40px"})
                                        @Html.ValidationMessageFor(model => model.descuento, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-8", @style = "text-align:left; font-size: 24px" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control col-md-10" } })
                                        @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group ml-3">
                    @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-12", @style = "text-align:left; font-size: 24px" })
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.imagen, new { @type = "file", @class = "form-control col-md-12", accept = ".jpg", id = "seleccionArchivos" })
                        @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.imagen)

                <div class="offset-md-2 col-md-8 ">
                    <div class="card" style="margin-top: 15px; margin-left: 25px; margin-right: 25px; background-color: rgb(255, 239, 239); border-color: #e33b5c">
                        <div class="card-body">
                            <label>Imagen:</label>

                            <div class="row">
                                <div class="offset-md-2 col-md-8">
                                    <div class="card" style=" margin-left: 5%; margin-right: 5%; background-color: rgb(255, 239, 239); height:300px">
                                        <div class="card-body text-center">
                                            <img src="@Url.Action("getImg",new { id = Model.id})" alt="@Model.nombre" height="250" width="300" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <hr />
                <div class="form-group text-center">
                    <input type="submit" value="Guardar Cambios" class="btn btn-danger" />

                </div>

            </div>
        </div>

    </div>
}

AutoShop/Views/producto/getExistencias.cshtml
@model IEnumerable<AutoShop.Models.Producto>

@{

    Layout = null;
}

<table class="table table-striped table-bordered">
    <tr class="bg-danger text-white">
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
        </tr>
    }

</table>

AutoShop/Views/producto/getProdMayor.cshtml
@model IEnumerable<AutoShop.Models.Producto>

@{

    Layout = null;
}


@foreach (var item in Model)
{
    <div class="card">
        <div class="card-header bg-danger text-white text-center">
            <h5 class="card-title"><b> Más Existencias </b></h5>
        </div>
        <div class="card-body text-center">
            <img class="card-img-top" src="@Url.Action("getImg",new { id = item.id})" alt="@item.id" height="205" width="50" />
            <hr>
            <p class="card-text">
                Nombre: @Html.DisplayFor(modelItem => item.nombre)
                <br>
                Categoría: @Html.DisplayFor(modelItem => item.Categoria.nombre)
                <br />
                Cantidad: @Html.DisplayFor(modelItem => item.cantidad)
            </p>

        </div>
    </div>
}

AutoShop/Views/producto/getProductos.cshtml
@model IEnumerable<AutoShop.Models.Producto>
@{

    Layout = null;
}


<table class="table table-striped table-bordered">
    <tr class="bg-danger text-white">
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.nombre)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.nombre)
            </td>
        </tr>
    }

</table>