AutoShop/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoShop.Models;

namespace AutoShop.Controllers
{
    public class CarroController : Controller
    {
        // GET: Carro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Agregar(int id, int cantidad)
        {
            ProductoCarro carro = new ProductoCarro();
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                Producto p = carro.find(id);
                string name = p.nombre;
                cart.Add(new Item { Producto = carro.find(id), Cantidad = cantidad });
                setItemCount(cart);
                Session["cart"] = cart;

            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Cantidad += cantidad;
                }
                else
                {
                    Producto P = carro.find(id);
                    string name = P.nombre;
                    cart.Add(new Item { Producto = carro.find(id), Cantidad = cantidad });
                }
                setItemCount(cart);
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        private int isExist(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Producto.id.Equals(id))
                    return i;
            return -1;
        }



        public ActionResult SumarUno(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            if (index != -1)
            {

                cart[index].Cantidad++;
                if (cart[index].Producto.cantidad == cart[index].Cantidad)
                {
                    cart[index].Cantidad--;
                }
                setItemCount(cart);

            }
            return RedirectToAction("Index");
        }

        public ActionResult QuitarUno(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            if (index != -1)
            {
                cart[index].Cantidad--;
                if (cart[index].Cantidad == 0)
                {
                    cart.RemoveAt(index);
                }
                setItemCount(cart);
            }
            return RedirectToAction("Index");
        }

        private void setItemCount(List<Item> cart)
        {
            int cont = 0;
            foreach (Item itm in cart)
            {
                cont = cont + itm.Cantidad;
            }
            Session["itemTotal"] = cont;
        }

        public ActionResult Quitar(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            setItemCount(cart);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
    }
}

AutoShop/Views/Carro/Index.cshtml
@using AutoShop.Models
@{
    ViewBag.Title = "Carrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card" style="background-color: #e33b5c;">
    <div class="card-header text-white text-center">
        <h2>Carro de Compra</h2>
    </div>
</div>

@{
    if (Session["cart"] != null && Convert.ToInt32(Session["itemTotal"]) != 0)
    {
        <table class="table table-bordered table-responsive">
            <thead>
                <tr style="background-color: #e33b5c; color: white;">
                    <th>Opción</th>
                    <th>Nombre</th>
                    <th>Foto</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                    <th>Añadir Uno</th>
                    <th>Quitar Uno</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Item item in (List<Item>)Session["cart"])
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Quitar", "Carro", new { id = item.Producto.id, @style="background-color: #e33b5c; color: white;" })"> Quitar</a>
                        </td>
                        <td>@item.Producto.nombre</td>
                        <td><img class="img-responsive" src="~/Content/img/productos/@item.Producto.imagen" /></td>
                        <td>@item.Producto.precio</td>
                        <td>@item.Cantidad</td>
                        <td>@(item.Producto.precio * item.Cantidad)</td>
                        <td>@Html.ActionLink("+", "SumarUno", new { id = item.Producto.id }, new { @class = "btn", @style = "background-color: #e33b5c; color: white;" })</td>
                        <td>@Html.ActionLink("-", "QuitarUno", new { id = item.Producto.id }, new { @class = "btn", @style = "background-color: #e33b5c; color: white;" })</td>
                    </tr>
                }
                <tr>
                    <td align="right" colspan="6">Total</td>
                    <td>
                        @{
                            List<Item> cart = (List<Item>)Session["cart"];
                            var total = cart.Sum(item => item.Producto.precio * item.Cantidad);
                        }
                        @total

                    </td>
                </tr>
            </tbody>
        </table>
    }
    else
    {
        <div class="jumbotron" style="font-size:20px; text-align:center; margin-top:40px">
            Aún no cuenta con productos, busca en nuestro catálogo y añádelo a tu carrito.
        </div>
    }
}

<br />
<a class="btn btn-warning" href="@Url.Action("Index","Home")"> Continuar Comprando</a>
<p style="float: right; color: white;">
    @{
        if (Session["cart"] != null && Convert.ToInt32(Session["itemTotal"]) != 0)
        {
            @Html.ActionLink("Confirmar Orden", "CrearOrden", "Pago", new { area = "" }, new { @class = "btn", @style = "background-color: #e33b5c; color: white;" })
        }
    }
</p>