AutoShop/Models/Envio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public int id { get; set; }
        public int id_orden_fk { get; set; }
        public int id_paq_fk { get; set; }
        public int id_cliente_fk { get; set; }
        public int id_direccion_fk { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string numero_guia { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Orden Orden { get; set; }
        public virtual Paqueteria Paqueteria { get; set; }
    }
}

AutoShop/Controllers/EnvioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoShop.Models;

namespace AutoShop.Controllers
{
    public class EnvioController : Controller
    {
        private contextAutoShop db = new contextAutoShop();

        // GET: Envio
        public ActionResult Index()
        {
            var envio = db.Envio.Where(e => e.fecha_envio == null).OrderBy(e => e.Orden.fecha_creacion).Include(e => e.Cliente).Include(e => e.Direccion).Include(e => e.Orden).Include(e => e.Paqueteria);
            return View(envio.ToList());
        }


        public ActionResult Index1()
        {
            var envio = db.Envio.Where(e => e.fecha_entrega == null && e.fecha_envio != null).OrderBy(e => e.fecha_envio).Include(e => e.Cliente).Include(e => e.Direccion).Include(e => e.Orden).Include(e => e.Paqueteria);
            return View(envio.ToList());
        }

        //Método para redireccionar a home
        public ActionResult Home()
        {
            List<Envio> query = (from i in db.Envio
                                 select i).ToList();

            var conteoTotalPaqs = query.Count();

            var enviosHoy = 0;
            var enviosSemana = 0;
            var enviosAnio = 0;
            var fechahoy = DateTime.Today.Date;
            var fechasemana = DateTime.Today.Date.AddDays(-7);
            var fechaanio = DateTime.Today.Date.AddYears(-1);
            foreach (Envio listado in (List<Envio>)query)
            {
                DateTime date = Convert.ToDateTime(listado.fecha_envio);
                if (date <= fechahoy)
                {
                    enviosHoy++;
                }
                if (date <= fechasemana)
                {
                    enviosSemana++;
                }
                if (date <= fechaanio)
                {
                    enviosAnio++;
                }
            }

            ViewBag.enviosHoy = enviosHoy;
            ViewBag.enviosSemana = enviosSemana;
            ViewBag.enviosAnio = enviosAnio;
            ViewBag.fechahoy = fechahoy;
            ViewBag.fechasemana = fechasemana;
            ViewBag.fechaanio = fechaanio;
            ViewBag.listadoPedidos = query;
            return View();
        }

        // GET: Envio/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Envio envio = db.Envio.Find(id);
            if (envio == null)
            {
                return HttpNotFound();
            }
            return View(envio);
        }

        // GET: Envio/Create
        public ActionResult Create()
        {
            ViewBag.id_cliente_fk = new SelectList(db.Cliente, "id", "contrasenia");
            ViewBag.id_direccion_fk = new SelectList(db.Direccion, "id", "estado");
            ViewBag.id_orden_fk = new SelectList(db.Orden, "id", "numero_confirmacion");
            ViewBag.id_paq_fk = new SelectList(db.Paqueteria, "id", "nombre");
            return View();
        }

        // POST: Envio/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_orden_fk,id_paq_fk,id_cliente_fk,id_direccion_fk,fecha_envio,fecha_entrega,numero_guia")] Envio envio)
        {
            if (ModelState.IsValid)
            {
                db.Envio.Add(envio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_cliente_fk = new SelectList(db.Cliente, "id", "contrasenia", envio.id_cliente_fk);
            ViewBag.id_direccion_fk = new SelectList(db.Direccion, "id", "estado", envio.id_direccion_fk);
            ViewBag.id_orden_fk = new SelectList(db.Orden, "id", "numero_confirmacion", envio.id_orden_fk);
            ViewBag.id_paq_fk = new SelectList(db.Paqueteria, "id", "nombre", envio.id_paq_fk);
            return View(envio);
        }
        // GET: Envio/Edit/5
        public ActionResult Edit1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Envio envio = db.Envio.Find(id);
            if (envio == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_direccion_fk = new SelectList(db.Direccion, "id", "estado", envio.id_direccion_fk);
            ViewBag.id_orden_fk = new SelectList(db.Orden, "id", "numero_confirmacion", envio.id_orden_fk);
            ViewBag.id_paq_fk = new SelectList(db.Paqueteria, "id", "nombre", envio.id_paq_fk);
            return View(envio);
        }


        // GET: Envio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Envio envio = db.Envio.Find(id);
            if (envio == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_direccion_fk = new SelectList(db.Direccion, "id", "estado", envio.id_direccion_fk);
            ViewBag.id_orden_fk = new SelectList(db.Orden, "id", "numero_confirmacion", envio.id_orden_fk);
            ViewBag.id_paq_fk = new SelectList(db.Paqueteria, "id", "nombre", envio.id_paq_fk);
            return View(envio);
        }

        // POST: Envio/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit1([Bind(Include = "id,id_orden_fk,id_paq_fk,id_cliente_fk,id_direccion_fk,fecha_envio,fecha_entrega,numero_guia")] Envio envio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(envio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_cliente_fk = new SelectList(db.Cliente, "id", "contrasenia", envio.id_cliente_fk);
            ViewBag.id_direccion_fk = new SelectList(db.Direccion, "id", "estado", envio.id_direccion_fk);
            ViewBag.id_orden_fk = new SelectList(db.Orden, "id", "numero_confirmacion", envio.id_orden_fk);
            ViewBag.id_paq_fk = new SelectList(db.Paqueteria, "id", "nombre", envio.id_paq_fk);
            return View(envio);
        }


        // POST: Envio/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_orden_fk,id_paq_fk,id_cliente_fk,id_direccion_fk,fecha_envio,fecha_entrega,numero_guia")] Envio envio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(envio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_cliente_fk = new SelectList(db.Cliente, "id", "contrasenia", envio.id_cliente_fk);
            ViewBag.id_direccion_fk = new SelectList(db.Direccion, "id", "estado", envio.id_direccion_fk);
            ViewBag.id_orden_fk = new SelectList(db.Orden, "id", "numero_confirmacion", envio.id_orden_fk);
            ViewBag.id_paq_fk = new SelectList(db.Paqueteria, "id", "nombre", envio.id_paq_fk);
            return View(envio);
        }

        // GET: Envio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Envio envio = db.Envio.Find(id);
            if (envio == null)
            {
                return HttpNotFound();
            }
            return View(envio);
        }

        // POST: Envio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Envio envio = db.Envio.Find(id);
            db.Envio.Remove(envio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoShop.Models;

namespace AutoShop.Controllers
{
    public class HomeController : Controller
    {
        private contextAutoShop db = new contextAutoShop();
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                string correo = User.Identity.Name;

                Cliente cliente = (from c in db.Cliente
                                   where c.correo == correo
                                   select c).ToList().FirstOrDefault();

                if (cliente == null)
                {
                    Empleado empleado = (from c in db.Empleado
                                         where c.correo == correo
                                         select c).ToList().FirstOrDefault();
                    Session["name"] = empleado.nombre;
                    RedirectToAction("Index", "Usuario", routeValues: new { email = correo });
                }
                else
                {

                    Session["name"] = cliente.nombre;
                }
            }
            else
            {

                Session["name"] = "";
            }
            if (Session["itemTotal"] == null)
            {
                Session["itemTotal"] = 0;
            }

            List<Producto> producto = (from c in db.Producto
                                       where c.descuento > 0
                                       select c).ToList();
            int cuenta = producto.Count;

            if (cuenta >= 4)
            {
                ViewBag.producto = producto.GetRange(0, 4);
            }
            else
            {
                ViewBag.producto = producto.GetRange(0, cuenta);
            }


            List<Producto> novedades = (from c in db.Producto
                                        select c).ToList();
            int cuentas = novedades.Count;
            if (cuentas >= 9)
            {
                ViewBag.novedades = novedades.GetRange(0, 8);
            }
            else
            {
                ViewBag.novedades = novedades.GetRange(0, cuentas);
            }


            var comentarios = db.Comentarios.Include(c => c.Cliente);

            ViewBag.comentarios = comentarios.ToList();
            return View();

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult getImg(int id)
        {
            Producto imgProd = (from i in db.Producto
                                 where i.id == id
                                 select i).ToList().FirstOrDefault();

            var fileToRetrieve = imgProd.imagen;
            if (fileToRetrieve == null)
            {
                return null;
            }
            else
            {
                return File(fileToRetrieve, "image/jpeg");
            }
        }
    }
}

AutoShop/Views/Envio/Edit.cshtml
@model AutoShop.Models.Envio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAlmacenEnvios.cshtml";
}


<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.css"
      rel="stylesheet" />
<!-- MDB -->
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"></script>


<div class="row">
    <div class="col-md-12">
        <br />
        <div align="left"><h1>Actualización de Fecha de Envío</h1></div><hr><br>
    </div>
    <div class="col-md-12">
        <div class="card border-danger">
            <div class="card-body" style="padding-left: 200px; padding-right: 200px; padding-top: 50px;padding-bottom: 50px;">
                <div class="card border-danger  form-horizontal">
                    <div class="card-header bg-danger text-white border-danger"><h3>Actualizar fecha de envío</h3></div>
                    <div class="card-body">
                        <br><br>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-md-12 pt-5" align="center">
                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-3" align="left">
                                            <p style="padding: 10px">ID Paquetería</p>
                                        </div>
                                        <div class="col-md-3">
                                            @Html.DropDownList("id_paq_fk", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.id_paq_fk, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-3" align="left">
                                            <p style="padding: 10px">Número de guía</p>
                                        </div>
                                        <div class="col-md-3">
                                            @Html.EditorFor(model => model.numero_guia, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.id_paq_fk, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-3" align="left">
                                            <p style="padding: 10px">Fecha de envío</p>
                                        </div>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(model => model.fecha_envio, new { @type = "date", @min = @Model.Orden.fecha_creacion.ToString("yyyy-MM-dd"), @class = "form-control datepicker" })
                                            @Html.ValidationMessageFor(model => model.fecha_envio, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" align="left">
                                    <br><br><br>
                                    <a class="btn btn-dark" style="width: 20%" type="submit" href="@Url.Action("Index", "Envio")">Regresar</a>
                                </div>
                                <div class="col-md-6" align="right">
                                    <br><br><br>
                                    <input class="btn btn-dark" style="width: 20%" type="submit" value="Guardar">
                                </div>
                            </div><br>

                        }
                    </div>
                </div>
            </div>
        </div>
        <br><br>
    </div>
</div>
<script src="~/Scripts/Generados/ImgPreview_EditP.js"></script>

AutoShop/Views/Envio/Edit1.cshtml
@model AutoShop.Models.Envio

@{
    ViewBag.Title = "Edit1";
    Layout = "~/Views/Shared/_LayoutAlmacenEnvios.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Envio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        @Html.HiddenFor(model => model.id_orden_fk)
        @Html.HiddenFor(model => model.id_paq_fk)
        @Html.HiddenFor(model => model.numero_guia)


        @Html.HiddenFor(model => model.id_cliente_fk)

        @Html.HiddenFor(model => model.id_direccion_fk)
        @Html.HiddenFor(model => model.fecha_envio)

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_entrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fecha_entrega, new { @type = "date", @min = @Model.fecha_envio.GetValueOrDefault().ToString("yyyy-MM-dd"), @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.fecha_envio, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index1")
</div>


<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.css"
      rel="stylesheet" />
<!-- MDB -->
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"></script>


<div class="row">
    <div class="col-md-12">
        <br />
        <div align="left"><h1>Actualización de Fecha de Entrega</h1></div><hr><br>
    </div>
    <div class="col-md-12">
        <div class="card border-danger">
            <div class="card-body" style="padding-left: 200px; padding-right: 200px; padding-top: 50px;padding-bottom: 50px;">
                <div class="card border-danger  form-horizontal">
                    <div class="card-header bg-danger text-white border-danger"><h3>Actualizar fecha de entrega</h3></div>
                    <div class="card-body">
                        <br><br>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-md-12 pt-5" align="center">
                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-3" align="left">
                                            <p style="padding: 10px"></p>
                                        </div>
                                        <div class="col-md-3">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-3" align="left">
                                            <p style="padding: 10px"></p>
                                        </div>
                                        <div class="col-md-3">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-3" align="left">
                                            <p style="padding: 10px">Fecha de entrega</p>
                                        </div>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(model => model.fecha_entrega, new { @type = "date", @min = @Model.fecha_envio.GetValueOrDefault().ToString("yyyy-MM-dd"), @class = "form-control datepicker" })
                                            @Html.ValidationMessageFor(model => model.fecha_envio, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6" align="left">
                                    <br><br><br>
                                    <a class="btn btn-dark" style="width: 20%" type="submit" href="@Url.Action("Index1", "Envio")">Regresar</a>
                                </div>
                                <div class="col-md-6" align="right">
                                    <br><br><br>
                                    <input class="btn btn-dark" style="width: 20%" type="submit" value="Guardar">
                                </div>
                            </div><br>

                        }
                    </div>
                </div>
            </div>
        </div>
        <br><br>
    </div>
</div>
<script src="~/Scripts/Generados/ImgPreview_EditP.js"></script>

AutoShop/Views/Envio/Home.cshtml
@using AutoShop.Models
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutAlmacenEnvios.cshtml";

    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutAlmacenEnvios.cshtml";

    DateTime dia = DateTime.Now;
    var hora = dia.Hour;
    string mensaje = "";
    if (hora < 12)
    {
        mensaje = "Buenos días";
    }
    if (hora >= 12)
    {
        mensaje = "Buenas tardes";
    }
    if (hora >= 19)
    {
        mensaje = "Buenas noches";
    }
    string name = @Session["usr"].ToString();
}
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.css"
      rel="stylesheet" />
<!-- MDB -->
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"></script>
<br /><br />

<div class="row" align="center">
    <div class="col-md-12">
        <div align="left"><h1>Home Envíos</h1></div><hr />
        <div style="text-align: justify;">
            <strong>@mensaje, @name, bienvenido.</strong><br />En este módulo, usted como empleado de Almacen, podrá manejar la información referente a envíos desde consultar aquellos pedidos sin enviar,
            registrar pedidos enviados, consultar pedidos enviados hasta registrar pedidos entregados.
        </div><br><br>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Index", "Envio", new { id = "add" })"
           class="btn btn-primary" style="height:120px; width:100%; font-size:28px; padding:40px; text-align:center;">
            Actualizar fecha de envío
        </a>
        <br />
        <br />
        <a href="@Url.Action("Index1", "Envio", new { id = "add" })"
           class="btn btn-warning" style="height:120px; width:100%; font-size:28px; padding:40px; text-align:center;">
            Actualizar fecha de entrega
        </a>
    </div>
    <div class="col-md-8" style="padding-left:200px;">
        <div class="row">
            <div class="card" style="width: 18rem; padding-left: 0; margin-right: 20px; padding-right: 0;">
                <img src="https://i1.wp.com/geeksroom.com/wp-content/uploads/2018/07/amazon-prime-boxes.jpg?resize=680%2C453&ssl=1" class="card-img-top" alt="..." height="200px">
                <div class="card-body" style="padding-bottom: 0px">
                    <p class="card-text" style="text-align: center;">
                        <strong>Envíos del día de hoy</strong><br>
                        <label style="text-align: center; font-size: 30px"> @ViewBag.enviosHoy</label>
                    </p>
                </div>
            </div>
            <div class="card" style="width: 18rem; padding-left: 0; margin-right: 20px; padding-right: 0;">
                <img src="https://elpais.com/economia/imagenes/2016/08/05/actualidad/1470397693_744949_1470675978_noticia_fotograma.jpg" class="card-img-top" alt="..." height="200px">
                <div class="card-body" style="padding-bottom: 0px">
                    <p class="card-text" style="text-align: center;">
                        <strong>Envíos de la semana</strong><br>
                        <label style="text-align: center; font-size: 30px"> @ViewBag.enviosSemana</label>
                    </p>
                </div>
            </div>
            <div class="card" style="width: 18rem; padding-left: 0; margin-right: 20px; padding-right: 0;">
                <img src="https://www.nextdaycargo.com/wp-content/uploads/2014/01/Screen-Shot-2014-01-27-at-9.37.42-AM.png" class="card-img-top" alt="..." height="200px">
                <div class="card-body" style="padding-bottom: 0px">
                    <p class="card-text" style="text-align: center;">
                        <strong>Envíos del año</strong><br>
                        <label style="text-align: center; font-size: 30px"> @ViewBag.enviosAnio</label>
                    </p>
                </div>
            </div>
        </div><br><br>
    </div>
</div>

<div class="row">
    <hr />
    <div class="col-md-12">
        <br>
        <div class="card">
            <div class="card-header bg-danger text-white">
                <br>
                <div align="left"><h3>Todos los pedidos sin enviar</h3></div>
            </div>
            <div class="card-body">
                @{
                    List<Envio> listadoPedidos = (List<Envio>)ViewBag.listadoPedidos;
                    if (listadoPedidos.Count() == 0)
                    {
                        <div class="jumbotron text-center" style="font-size:30px">No hay pedidos sin enviar</div>
                    }
                    else
                    {

                        <table class="table table-dark table-striped table-hover table-bordered">
                            <thead>
                                <tr class="bg-danger text-white">
                                    <th>ID Cliente</th>
                                    <th>Nombre de cliente</th>
                                    <th>Paquetería</th>
                                    <th>Orden de cliente</th>
                                    <th>Dirección</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in listadoPedidos)
                                {
                                    if (item.fecha_envio == null)
                                    {

                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.id_cliente_fk)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Cliente.nombre)
                                                @Html.DisplayFor(modelItem => item.Cliente.apPaterno)
                                                @Html.DisplayFor(modelItem => item.Cliente.apMaterno)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Paqueteria.nombre)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.id_orden_fk)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Direccion.calle)
                                                @Html.DisplayFor(modelItem => item.Direccion.numExterior)
                                                @Html.DisplayFor(modelItem => item.Direccion.colonia)
                                                @Html.DisplayFor(modelItem => item.Direccion.municipio)
                                                @Html.DisplayFor(modelItem => item.Direccion.estado)
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    }
                }
            </div>
        </div>
    </div>
</div>